### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by FarhadHP** [crgeary/inspector#1]
1) `npm install`
2) `npm start`

```
Failed to compile
./src/App.js
30:32-43 'yoastseo' does not contain an export named 'SEOAssessor'.
```

**Comment by crgeary** [comment]
This is because newer versions of `YoastSEO.js` stopped exporting the `SEOAssessor`. I've updated this repo to lock versions to ones that worked when I created it.

I think they added it back in, but I can't find the issue that we raised about it to be 100% sure. However, if you re-clone this repo, it should work again for you (but it will be out of date).
